### ISSUE TITLE
CraftBlockProjectileSource cannot be cast to org.bukkit.entity.LivingEntity when mob hit by an arrow from a dispenser

### ISSUE THREAD

**Issue by RoboMWM** [ShadowDog007/MobManager#30]
When a mob is hit by an arrow from a dispenser...

``` txt
[10:51:28 ERROR]: Could not pass event EntityDamageByEntityEvent to MobManager v3.0.3                                                                                                                       
org.bukkit.event.EventException                                                                                                                                                                             
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                  
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                       
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                    
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                  
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                  
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                    
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                       
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                     
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                               
        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1107) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                            
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:734) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                  
        at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                 
        at net.minecraft.server.v1_8_R3.EntityZombie.damageEntity(EntityZombie.java:167) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                  
        at net.minecraft.server.v1_8_R3.EntityArrow.t_(EntityArrow.java:250) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                              
        at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1642) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                          
        at net.minecraft.server.v1_8_R3.World.g(World.java:1609) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                                          
        at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1446) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                               
        at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:600) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                    
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:844) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                       
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                       
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                       
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                     
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]                                                                                                                                               
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.projectiles.CraftBlockProjectileSource cannot be cast to org.bukkit.entity.LivingEntity                                             
        at com.forgenz.mobmanager.abilities.listeners.AbilitiesMobListener.setDamageMulti(AbilitiesMobListener.java:253) ~[?:?]                                                                             
        at sun.reflect.GeneratedMethodAccessor447.invoke(Unknown Source) ~[?:?]                                                                                                                             
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]                                                                                              
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]                                                                                                                                   
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[PaperSpigot.jar:git-PaperSpigot-314212b-07c3001]                                                                  
        ... 22 more
```

**Comment by RoboMWM** [comment]
Oh, I see the new version has yet to be uploaded...
